namespace LightingChartSamples.Scatter.AccordPcaScatter
{
    partial class AccordScatterMain
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.FlowLayoutPanel commandPanel;
        private System.Windows.Forms.Label titleLabel;
        private System.Windows.Forms.Label paramTypeCaptionLabel;
        private System.Windows.Forms.RadioButton responseRadioButton;
        private System.Windows.Forms.RadioButton defectRadioButton;
        private System.Windows.Forms.Label draftNoCaptionLabel;
        private System.Windows.Forms.TextBox draftNoTextBox;
        private System.Windows.Forms.Button searchButton;
        private System.Windows.Forms.Button chartDrawButton;
        private System.Windows.Forms.Button refreshAllButton;
        private System.Windows.Forms.Button sampleDataButton;
        private System.Windows.Forms.Label knnCaptionLabel;
        private System.Windows.Forms.ComboBox knnAlgorithmComboBox;
        private System.Windows.Forms.CheckBox preferMemoryCheckBox;
        private System.Windows.Forms.Label summaryLabel;
        private System.Windows.Forms.Panel chartHost;
        private System.Windows.Forms.DataGridView nearestNeighborGrid;
        private System.Windows.Forms.Panel busyOverlayPanel;
        private System.Windows.Forms.Label busyOverlayLabel;
        private System.Windows.Forms.ProgressBar busyProgressBar;

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.commandPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.titleLabel = new System.Windows.Forms.Label();
            this.paramTypeCaptionLabel = new System.Windows.Forms.Label();
            this.responseRadioButton = new System.Windows.Forms.RadioButton();
            this.defectRadioButton = new System.Windows.Forms.RadioButton();
            this.draftNoCaptionLabel = new System.Windows.Forms.Label();
            this.draftNoTextBox = new System.Windows.Forms.TextBox();
            this.searchButton = new System.Windows.Forms.Button();
            this.chartDrawButton = new System.Windows.Forms.Button();
            this.refreshAllButton = new System.Windows.Forms.Button();
            this.sampleDataButton = new System.Windows.Forms.Button();
            this.knnCaptionLabel = new System.Windows.Forms.Label();
            this.knnAlgorithmComboBox = new System.Windows.Forms.ComboBox();
            this.preferMemoryCheckBox = new System.Windows.Forms.CheckBox();
            this.summaryLabel = new System.Windows.Forms.Label();
            this.chartHost = new System.Windows.Forms.Panel();
            this.nearestNeighborGrid = new System.Windows.Forms.DataGridView();
            this.rootLayout.SuspendLayout();
            this.commandPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nearestNeighborGrid)).BeginInit();
            this.SuspendLayout();
            this.rootLayout.BackColor = System.Drawing.Color.White;
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.commandPanel, 0, 0);
            this.rootLayout.Controls.Add(this.chartHost, 0, 1);
            this.rootLayout.Controls.Add(this.nearestNeighborGrid, 0, 2);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Location = new System.Drawing.Point(0, 0);
            this.rootLayout.Name = "rootLayout";
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 86F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 156F));
            this.rootLayout.Size = new System.Drawing.Size(1360, 820);
            this.rootLayout.TabIndex = 0;
            this.commandPanel.BackColor = System.Drawing.Color.White;
            this.commandPanel.Controls.Add(this.titleLabel);
            this.commandPanel.Controls.Add(this.paramTypeCaptionLabel);
            this.commandPanel.Controls.Add(this.responseRadioButton);
            this.commandPanel.Controls.Add(this.defectRadioButton);
            this.commandPanel.Controls.Add(this.draftNoCaptionLabel);
            this.commandPanel.Controls.Add(this.draftNoTextBox);
            this.commandPanel.Controls.Add(this.searchButton);
            this.commandPanel.Controls.Add(this.chartDrawButton);
            this.commandPanel.Controls.Add(this.refreshAllButton);
            this.commandPanel.Controls.Add(this.sampleDataButton);
            this.commandPanel.Controls.Add(this.knnCaptionLabel);
            this.commandPanel.Controls.Add(this.knnAlgorithmComboBox);
            this.commandPanel.Controls.Add(this.preferMemoryCheckBox);
            this.commandPanel.Controls.Add(this.summaryLabel);
            this.commandPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.commandPanel.FlowDirection = System.Windows.Forms.FlowDirection.LeftToRight;
            this.commandPanel.Location = new System.Drawing.Point(0, 0);
            this.commandPanel.Margin = new System.Windows.Forms.Padding(0);
            this.commandPanel.Name = "commandPanel";
            this.commandPanel.Padding = new System.Windows.Forms.Padding(18, 10, 18, 4);
            this.commandPanel.Size = new System.Drawing.Size(1360, 86);
            this.commandPanel.TabIndex = 0;
            this.commandPanel.WrapContents = true;
            this.titleLabel.AutoSize = true;
            this.titleLabel.Font = new System.Drawing.Font("Malgun Gothic", 11F, System.Drawing.FontStyle.Bold);
            this.titleLabel.Location = new System.Drawing.Point(18, 16);
            this.titleLabel.Margin = new System.Windows.Forms.Padding(0, 6, 28, 0);
            this.titleLabel.Name = "titleLabel";
            this.titleLabel.Size = new System.Drawing.Size(134, 20);
            this.titleLabel.TabIndex = 0;
            this.titleLabel.Text = "Accord PCA Scatter";
            this.paramTypeCaptionLabel.AutoSize = true;
            this.paramTypeCaptionLabel.Location = new System.Drawing.Point(180, 18);
            this.paramTypeCaptionLabel.Margin = new System.Windows.Forms.Padding(0, 8, 8, 0);
            this.paramTypeCaptionLabel.Name = "paramTypeCaptionLabel";
            this.paramTypeCaptionLabel.Size = new System.Drawing.Size(72, 15);
            this.paramTypeCaptionLabel.TabIndex = 1;
            this.paramTypeCaptionLabel.Text = "PARAM_TYP";
            this.responseRadioButton.AutoSize = true;
            this.responseRadioButton.Checked = true;
            this.responseRadioButton.Location = new System.Drawing.Point(262, 17);
            this.responseRadioButton.Margin = new System.Windows.Forms.Padding(2, 7, 10, 0);
            this.responseRadioButton.Name = "responseRadioButton";
            this.responseRadioButton.Size = new System.Drawing.Size(82, 19);
            this.responseRadioButton.TabIndex = 2;
            this.responseRadioButton.TabStop = true;
            this.responseRadioButton.Text = "RESPONSE";
            this.responseRadioButton.UseVisualStyleBackColor = true;
            this.responseRadioButton.CheckedChanged += new System.EventHandler(this.ParameterRadioButton_CheckedChanged);
            this.defectRadioButton.AutoSize = true;
            this.defectRadioButton.Location = new System.Drawing.Point(356, 17);
            this.defectRadioButton.Margin = new System.Windows.Forms.Padding(2, 7, 20, 0);
            this.defectRadioButton.Name = "defectRadioButton";
            this.defectRadioButton.Size = new System.Drawing.Size(66, 19);
            this.defectRadioButton.TabIndex = 3;
            this.defectRadioButton.Text = "DEFECT";
            this.defectRadioButton.UseVisualStyleBackColor = true;
            this.defectRadioButton.CheckedChanged += new System.EventHandler(this.ParameterRadioButton_CheckedChanged);
            this.draftNoCaptionLabel.AutoSize = true;
            this.draftNoCaptionLabel.Location = new System.Drawing.Point(442, 18);
            this.draftNoCaptionLabel.Margin = new System.Windows.Forms.Padding(0, 8, 8, 0);
            this.draftNoCaptionLabel.Name = "draftNoCaptionLabel";
            this.draftNoCaptionLabel.Size = new System.Drawing.Size(62, 15);
            this.draftNoCaptionLabel.TabIndex = 4;
            this.draftNoCaptionLabel.Text = "DRAFT_NO";
            this.draftNoTextBox.Location = new System.Drawing.Point(512, 14);
            this.draftNoTextBox.Margin = new System.Windows.Forms.Padding(0, 4, 10, 0);
            this.draftNoTextBox.Name = "draftNoTextBox";
            this.draftNoTextBox.Size = new System.Drawing.Size(160, 23);
            this.draftNoTextBox.TabIndex = 5;
            this.searchButton.Location = new System.Drawing.Point(682, 13);
            this.searchButton.Margin = new System.Windows.Forms.Padding(0, 3, 8, 0);
            this.searchButton.Name = "searchButton";
            this.searchButton.Size = new System.Drawing.Size(96, 28);
            this.searchButton.TabIndex = 6;
            this.searchButton.Text = "Draft Search";
            this.searchButton.UseVisualStyleBackColor = true;
            this.searchButton.Click += new System.EventHandler(this.SearchButton_Click);
            this.chartDrawButton.Location = new System.Drawing.Point(786, 13);
            this.chartDrawButton.Margin = new System.Windows.Forms.Padding(0, 3, 8, 0);
            this.chartDrawButton.Name = "chartDrawButton";
            this.chartDrawButton.Size = new System.Drawing.Size(96, 28);
            this.chartDrawButton.TabIndex = 7;
            this.chartDrawButton.Text = "Chart Draw";
            this.chartDrawButton.UseVisualStyleBackColor = true;
            this.chartDrawButton.Click += new System.EventHandler(this.ChartDrawButton_Click);
            this.refreshAllButton.Location = new System.Drawing.Point(890, 13);
            this.refreshAllButton.Margin = new System.Windows.Forms.Padding(0, 3, 8, 0);
            this.refreshAllButton.Name = "refreshAllButton";
            this.refreshAllButton.Size = new System.Drawing.Size(106, 28);
            this.refreshAllButton.TabIndex = 8;
            this.refreshAllButton.Text = "Refresh All";
            this.refreshAllButton.UseVisualStyleBackColor = true;
            this.refreshAllButton.Click += new System.EventHandler(this.RefreshAllButton_Click);
            this.sampleDataButton.Location = new System.Drawing.Point(1004, 13);
            this.sampleDataButton.Margin = new System.Windows.Forms.Padding(0, 3, 8, 0);
            this.sampleDataButton.Name = "sampleDataButton";
            this.sampleDataButton.Size = new System.Drawing.Size(106, 28);
            this.sampleDataButton.TabIndex = 9;
            this.sampleDataButton.Text = "Virtual Data";
            this.sampleDataButton.UseVisualStyleBackColor = true;
            this.sampleDataButton.Click += new System.EventHandler(this.SampleDataButton_Click);
            this.knnCaptionLabel.AutoSize = true;
            this.knnCaptionLabel.Location = new System.Drawing.Point(1118, 18);
            this.knnCaptionLabel.Margin = new System.Windows.Forms.Padding(0, 8, 8, 0);
            this.knnCaptionLabel.Name = "knnCaptionLabel";
            this.knnCaptionLabel.Size = new System.Drawing.Size(31, 15);
            this.knnCaptionLabel.TabIndex = 10;
            this.knnCaptionLabel.Text = "KNN";
            this.knnAlgorithmComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.knnAlgorithmComboBox.FormattingEnabled = true;
            this.knnAlgorithmComboBox.Location = new System.Drawing.Point(1157, 14);
            this.knnAlgorithmComboBox.Margin = new System.Windows.Forms.Padding(0, 4, 10, 0);
            this.knnAlgorithmComboBox.Name = "knnAlgorithmComboBox";
            this.knnAlgorithmComboBox.Size = new System.Drawing.Size(116, 23);
            this.knnAlgorithmComboBox.TabIndex = 11;
            this.preferMemoryCheckBox.AutoSize = true;
            this.preferMemoryCheckBox.Checked = true;
            this.preferMemoryCheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this.preferMemoryCheckBox.Location = new System.Drawing.Point(1283, 17);
            this.preferMemoryCheckBox.Margin = new System.Windows.Forms.Padding(0, 7, 20, 0);
            this.preferMemoryCheckBox.Name = "preferMemoryCheckBox";
            this.preferMemoryCheckBox.Size = new System.Drawing.Size(96, 19);
            this.preferMemoryCheckBox.TabIndex = 12;
            this.preferMemoryCheckBox.Text = "Memory First";
            this.preferMemoryCheckBox.UseVisualStyleBackColor = true;
            this.summaryLabel.AutoSize = false;
            this.summaryLabel.ForeColor = System.Drawing.Color.FromArgb(80, 80, 80);
            this.summaryLabel.Location = new System.Drawing.Point(148, 45);
            this.summaryLabel.Margin = new System.Windows.Forms.Padding(130, 4, 0, 0);
            this.summaryLabel.Name = "summaryLabel";
            this.summaryLabel.Size = new System.Drawing.Size(1120, 28);
            this.summaryLabel.TabIndex = 13;
            this.summaryLabel.Text = "Ready. This form uses Accord.NET PCA only.";
            this.summaryLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.chartHost.BackColor = System.Drawing.Color.White;
            this.chartHost.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartHost.Location = new System.Drawing.Point(3, 89);
            this.chartHost.Name = "chartHost";
            this.chartHost.Padding = new System.Windows.Forms.Padding(14, 8, 14, 8);
            this.chartHost.Size = new System.Drawing.Size(1354, 572);
            this.chartHost.TabIndex = 1;
            this.nearestNeighborGrid.AllowUserToAddRows = false;
            this.nearestNeighborGrid.AllowUserToDeleteRows = false;
            this.nearestNeighborGrid.AllowUserToResizeRows = false;
            this.nearestNeighborGrid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.nearestNeighborGrid.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.None;
            this.nearestNeighborGrid.BackgroundColor = System.Drawing.Color.White;
            this.nearestNeighborGrid.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.nearestNeighborGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.nearestNeighborGrid.Location = new System.Drawing.Point(3, 667);
            this.nearestNeighborGrid.MultiSelect = false;
            this.nearestNeighborGrid.Name = "nearestNeighborGrid";
            this.nearestNeighborGrid.ReadOnly = true;
            this.nearestNeighborGrid.RowHeadersVisible = false;
            this.nearestNeighborGrid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.nearestNeighborGrid.Size = new System.Drawing.Size(1354, 150);
            this.nearestNeighborGrid.TabIndex = 2;
            this.nearestNeighborGrid.SelectionChanged += new System.EventHandler(this.NearestNeighborGrid_SelectionChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1360, 820);
            this.Controls.Add(this.rootLayout);
            this.Font = new System.Drawing.Font("Malgun Gothic", 9F, System.Drawing.FontStyle.Regular);
            this.MinimumSize = new System.Drawing.Size(1100, 700);
            this.Name = "AccordScatterMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "AccordScatterMain - Accord.NET PCA Scatter";
            this.rootLayout.ResumeLayout(false);
            this.commandPanel.ResumeLayout(false);
            this.commandPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nearestNeighborGrid)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
