SELECT
    M.DRAFT_NO,
    J.ENGR_RSLT_VAL,
    J.RSLT_CD,
    M.PARAM_TYP,
    M.CONV_EXPER_CTN
FROM TASADM.PCCB_INFER_RSLT_INF M
JOIN TASADM.PCCB_JUDGE_RSLT_INF J
    ON M.DRAFT_NO = J.DRAFT_NO
   AND M.PARAM_TYP = J.PARAM_TYP
WHERE M.CHG_TM > SYSDATE - 10
  AND J.ENGR_RSLT_VAL IS NOT NULL
  AND M.CONV_EXPER_CTN IS NOT NULL
